server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: fair-dice

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gdpr
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
      max-lifetime: 10000
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:import.sql

  jackson:
    serialization:
      indent_output: true

  thymeleaf:
    enabled: false
