package org.aueb.fair.dice.infrastructure.adapter.secondary.persistence.entity.user;

import jakarta.persistence.*;
import lombok.*;
/**
 * Entity class representing an application user.
 *
 * Maps to the {@code APPLICATION_USERS} table in the database.
 * Stores user credentials and basic identity information.
 */
@Entity
@Table(name = "APPLICATION_USERS")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class UserEntity {

    /**
     * The primary key of the user record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The first name of the user.
     * Mapped to the {@code USER_FIRST_NAME} column.
     */
    @Column(name = "USER_FIRST_NAME")
    private String firstName;

    /**
     * The last name of the user.
     * Mapped to the {@code USER_LAST_NAME} column.
     */
    @Column(name = "USER_LAST_NAME")
    private String lastName;

    /**
     * The unique username of the user.
     * Used for login and identification.
     * Cannot be null.
     */
    @Column(name = "USERNAME", unique = true, nullable = false)
    private String username;

    /**
     * The user's encoded password.
     * Cannot be null. Stored as a bcrypt or similar secure hash.
     */
    @Column(name = "USER_PASSWORD", nullable = false)
    private String password;

    /**
     * The user email.
     */
    @Column(name = "USER_EMAIL", nullable = false)
    private String email;
}
