package org.aueb.fair.dice.infrastructure.adapter.secondary.persistence.entity.session;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;

@Entity
@Table(name = "SESSIONS")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SessionEntity implements Serializable {

    /**
     * The primary key of the user record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "SESSION_NOTES")
    private String notes;

    //@ManyToOne
    //unidirectional
    // @JoinColumn( user id)

    // TODO Other fields
}
